services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: job_application_tracker_app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      SERVER_NAME: ":80, localhost"

      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}

      DATABASE_URL: "mysql://symfony:${MYSQL_PASSWORD}@db:3306/job_application_tracker?serverVersion=mariadb-12.3.3&charset=utf8mb4"
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12.3.3
    container_name: job_application_tracker_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: job_application_tracker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
  db_data:
