services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: job_application_tracker_app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      SERVER_NAME: ":80, localhost"
      PHP_IDE_CONFIG: serverName=job-application-tracker
    extra_hosts:
      - host.docker.internal:host-gateway
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12.3
    container_name: job_application_tracker_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_application_tracker
      MYSQL_USER: job_application_tracker
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
  database_data:
