name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl, pdo_mysql, zip
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: PHP CS Fixer
        run: composer ci:php-cs-fixer

      - name: PHPStan
        run: composer ci:phpstan

      - name: Deptrac
        run: composer ci:deptrac

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl, pdo_mysql, zip
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: PHPUnit
        if: ${{ hashFiles('tests/**/*Test.php') == '' }}
        run: composer ci:phpunit

      - name: PHPUnit with coverage
        if: ${{ hashFiles('tests/**/*Test.php') != '' }}
        run: composer ci:coverage
        env:
          XDEBUG_MODE: coverage

      - name: Upload coverage to Codecov
        if: ${{ hashFiles('tests/**/*Test.php') != '' }}
        uses: codecov/codecov-action@v5
        with:
          files: var/coverage/cobertura.xml
          flags: tests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
