name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl, pdo_mysql, zip
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: PHP CS Fixer
        run: composer ci:php-cs-fixer

      - name: PHPStan
        run: composer ci:phpstan

      - name: Deptrac
        run: composer ci:deptrac

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:12.3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: job_application_tracker
          MYSQL_USER: job_application_tracker
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/job_application_tracker?serverVersion=12.3.3-MariaDB&charset=utf8mb4

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl, pdo_mysql, zip
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare test database
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
          for token in $(seq 1 "$(nproc)"); do
            TEST_TOKEN=$token php bin/console doctrine:database:create --if-not-exists --env=test
            TEST_TOKEN=$token php bin/console doctrine:migrations:migrate --no-interaction --env=test
          done

      - name: PHPUnit
        if: ${{ hashFiles('tests/**/*Test.php') == '' }}
        run: composer ci:phpunit

      - name: PHPUnit with coverage
        if: ${{ hashFiles('tests/**/*Test.php') != '' }}
        run: composer ci:coverage
        env:
          XDEBUG_MODE: coverage

      - name: Upload coverage to Codecov
        if: ${{ hashFiles('tests/**/*Test.php') != '' }}
        uses: codecov/codecov-action@v5
        with:
          files: var/coverage/cobertura.xml
          flags: tests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
